# Generated by Django 5.2.3 on 2025-06-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.TextField(choices=[('PRIVATE ROOM', 'Private Room'), ('CONFERENCE_ROOM', 'Conference Room'), ('SHARED_DESK', 'Shared Desk')])),
                ('room_nos', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.TextField(choices=[('9 AM - 10 AM', 'Nine Am Ten Am'), ('10 AM - 11 AM', 'Ten Am Eleven Am'), ('11 AM - 12 PM', 'Eleven Am Twelve Pm'), ('12 PM - 1 PM', 'Twelve Pm One Pm'), ('1 PM - 2 PM', 'One Pm Two Pm'), ('2 PM - 3 PM', 'Two Pm Three Pm'), ('3 PM - 4 PM', 'Three Pm Four Pm'), ('4 PM - 5 PM', 'Four Pm Five Pm'), ('5 PM - 6 PM', 'Five Pm Six Pm')])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.BigIntegerField()),
                ('user_type', models.TextField(choices=[('USER', 'User'), ('TEAM', 'Team')])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.slot')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')])),
                ('is_admin', models.BooleanField(default=False)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.team')),
            ],
        ),
    ]
