# Generated by Django 5.2.3 on 2025-06-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookings',
            unique_together={('room', 'slot', 'timestamp')},
        ),
    ]
