# Generated by Django 5.2.3 on 2025-06-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_bookings_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookings',
            unique_together=set(),
        ),
    ]
